name: Release

on:
  push:
    tags:
      - v**

jobs:
  auto-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Release
        uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77 # v1
        with:
          generate_release_notes: true

  container-main:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@1e2cf88855aedd3146d502c2252ce23978743126 # main
    with:
      name: audittail
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: images/audittail/Dockerfile
      platforms: linux/amd64,linux/arm64

